# vim:ft=kitty

## name:     Catppuccin-Mocha
## author:   Pocco81 (https://github.com/Pocco81)
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/mocha.conf
## blurb:    Soothing pastel theme for the high-spirited!


# The basic colors
foreground              #CDD6F4
background              #0A0E1A
selection_foreground    #11111a
selection_background    #F5E0DC

# Cursor colors
cursor                  #00F0FF
cursor_text_color       #08080C

# URL underline color when hovering with mouse
url_color               #FF2E97

# Kitty window border colors
active_border_color     #00F0FF
inactive_border_color   #00F0FF
bell_border_color       #FF2E97

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #E8E8F0
active_tab_background   #0A0E1A
inactive_tab_foreground #4A5A6D
inactive_tab_background #0A0E1A
tab_bar_background      none
tab_bar_margin_color    none

# Colors for marks (marked text in the terminal)
mark1_foreground #08080C
mark1_background #B4BEFE
mark2_foreground #08080C
mark2_background #CBA6F7
mark3_foreground #08080C
mark3_background #74C7EC

# The 16 terminal colors

# black
color0 #45475A
color8 #585B70

# red
color1 #F38BA8
color9 #F38BA8

# green
color2  #A6E3A1
color10 #A6E3A1

# yellow
color3  #F9E2AF
color11 #F9E2AF

# blue (neon pink)
color4  #FF2E97
color12 #FF2E97

# magenta (neon pink)
color5  #FF2E97
color13 #FF2E97

# cyan
color6  #94E2D5
color14 #94E2D5

# white
color7  #BAC2DE
color15 #A6ADC8
